### ISSUE TITLE
Doesn't appear to work with reactiveVal() or reactiveValues()

### ISSUE THREAD

**Issue by cpsievert** [dgkf/scriptgloss#11]
A minimal example...if you click the action button several times, then click 'Show Code', it yields: `rv <- reactiveVal(0); rv()`. If I've clicked three times, I'd expect it to yield something similar to: `rv <- 3; rv`

```r
library(shiny)
library(scriptgloss)

ui <- fluidPage(
  scriptglossJS(),
  showCodeButton("show_code"),
  actionButton("click", "Click me!"),
  textOutput("n")
)

server <- function(input, output, session) {
  rv <- reactiveVal(0)
  observeEvent(input$click, { rv(rv() + 1) })
  output$n <- renderText(rv())
  observeEvent(input$show_code, show_code_modal(server))
}

shinyApp(ui, server)
```

BTW, `shiny::reactiveVal()` and `shiny::reactiveValues()` are similar in principle to `input` values, so it seems like it might be possible to handle them in a similar way?

**Comment by dgkf** [comment]
Thanks @cpsievert. 

Taking a quick look at my code, you're absolutely right- this was a glaring omission in my attempt to cover the shiny functions. I think it should be pretty manageable to come to a more reasonable implementation.

When the code is exported, I think it would probably be easiest to convert the reactiveVal into a nullary function that returns the value at the time of generation, so the code might look like this:

```r
rv <- function() { 3 }
rv()
```

The nullary function is a convenience so that we don't need to walk the syntax tree to find instances of `rv` to strip the `()`'s off of. It would be doable, but for a first pass I'd probably just go the function route.

How would you feel about generated code that looked like that? Is there a particular reason why having it as a function wouldn't be suitable beyond just aesthetics?

**Comment by cpsievert** [comment]
> Is there a particular reason why having it as a function wouldn't be suitable beyond just aesthetics?

I don't think so...seems like a reasonable thing to do

**Comment by dgkf** [comment]
Okay - it should be fixed now.

Also, I discovered another bug when trying to use `render*` functions with single line expressions (such as `renderText(rv())` from your example). Thanks for taking a look and helping me to discover these edge cases that I had overlooked! 

Please let me know if you see anything else that looks problematic. For big things like this, I'm happy to hop on a bug fix.
