### ISSUE TITLE
bug in parse_shiny_files

### ISSUE THREAD

**Issue by kieranjmartin** [dgkf/scriptgloss#4]
This argument doesn't work as intended

     files = file.path(getwd(), c('app.R', 'global.R')))

if this returns more than one object, lapplying over this won't work, as it returns a list of length 1 with multiple objects in it, which causes parse to error. I think you might need to use unlist(recursive=FALSE) to fix this. Note that as written as well you pick up things like a project file with "app" in it, as occurred to me during testing!

To reproduce this, make a basic app with project name myshinyapp and I think this will trigger it!

**Comment by dgkf** [comment]
Thanks for filing this, @kieranjmartin 

I'm not sure I completely understand the error. It seems like you're addressing a couple things - first that `lapply`'ing over the result of [the `file.path` call](https://github.com/dgkf/scriptgloss/blob/3e58f11df1fa07bce6550ae54c1549d9bf2222b1/R/code-generate-static-code.R#L126) might not be working as intended, and second that [`list.files`](https://github.com/dgkf/scriptgloss/blob/3e58f11df1fa07bce6550ae54c1549d9bf2222b1/R/code-generate-static-code.R#L130) might be inadvertently picking up a project file with the text "app" anywhere in the filename instead of exclusively "app.R" files.

I tried to boil down the first question with this code and it seems to work as intended.

```r
 > lapply(file.path("a", c("b", "cdef")), nchar)
#> [[1]]
#> [1] 3
#> 
#> [[2]]
#> [1] 6
```

For the latter - you are indeed correct. I'll convert the filenames to `^app.R$` to ensure it matches the exact name and not other files that contain that pattern.

**Comment by kieranjmartin** [comment]
Hi @dgkf ,

Sorry, I wasn't clear before, and identified a bug in the wrong place. I think your fix will probably remove this issue, but if you have two objects matching one of the search terms, the code

    files <- Filter(length, lapply(files, function(i)
      list.files(dirname(i), basename(i), full.names = TRUE, ignore.case = TRUE)
    ))

Will return a list with one entry, with 2 matches.

So eg if I have two files named app.R and myapp.R in the same space, and run this code

```
files = file.path(getwd(), c('app.R', 'global.R'))

files <- Filter(length, lapply(files, function(i)
  list.files(dirname(i), basename(i), full.names = TRUE, ignore.case = TRUE)
))

# parse code from discovered files
files <- lapply(files, function(f) {
  f <- parse(f)
  f <- as.call(c(list(quote(`{`)), f))
})
```

Then the second line returns the object

`[[1]]
[1] "/opt/bee/home_nas/martik32/reprex/app.R"   "/opt/bee/home_nas/martik32/reprex/myapp.R"`

which causes the last line to error. If you always get unique hits then I think this is no longer a problem.
